// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Procurar produtos",
  description: "Procura produtos por c\xF3digo, nome ou categoria e devolve stock atual, stock avariado e n\xFAmero de colis.",
  inputSchema: {
    query: z.string().trim().min(1).describe("C\xF3digo, nome ou parte do nome do produto."),
    limit: z.number().int().min(1).max(50).default(20).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const term = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await supabase.from("products").select("code,name,category,total_colis,current_stock,damaged_stock,min_stock,location").or(`code.ilike.%${term}%,name.ilike.%${term}%,category.ilike.%${term}%`).order("name").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/product-stock.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var product_stock_default = defineTool2({
  name: "product_stock_by_location",
  title: "Stock por localiza\xE7\xE3o",
  description: "Devolve o stock de um produto (por c\xF3digo exato) detalhado por localiza\xE7\xE3o e n\xFAmero de coli.",
  inputSchema: {
    code: z2.string().trim().min(1).describe("C\xF3digo exato do produto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: product, error: productError } = await supabase.from("products").select("id,code,name,category,total_colis,current_stock,damaged_stock").eq("code", code).maybeSingle();
    if (productError) return { content: [{ type: "text", text: productError.message }], isError: true };
    if (!product) {
      return { content: [{ type: "text", text: `Produto ${code} n\xE3o encontrado.` }], isError: true };
    }
    const { data: counts, error: countsError } = await supabase.from("counts").select("location,colis_number,quantity,updated_at").eq("product_id", product.id).order("location", { nullsFirst: true }).order("colis_number");
    if (countsError) return { content: [{ type: "text", text: countsError.message }], isError: true };
    const payload = { product, locations: counts ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/low-stock.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
var low_stock_default = defineTool3({
  name: "list_low_stock",
  title: "Produtos em rutura ou negativos",
  description: "Lista produtos com stock abaixo de zero ou abaixo de um limite indicado, para reposi\xE7\xE3o e corre\xE7\xF5es.",
  inputSchema: {
    threshold: z3.number().int().default(0).describe("Mostrar produtos com stock igual ou inferior a este valor."),
    limit: z3.number().int().min(1).max(200).default(50).describe("N\xFAmero m\xE1ximo de resultados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ threshold, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("code,name,category,current_stock,damaged_stock,min_stock").lte("current_stock", threshold ?? 0).order("current_stock").limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/recent-movements.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var recent_movements_default = defineTool4({
  name: "recent_stock_movements",
  title: "Movimentos de stock recentes",
  description: "Lista os movimentos de stock mais recentes (entradas, sa\xEDdas, ajustes), opcionalmente filtrados por c\xF3digo de produto.",
  inputSchema: {
    code: z4.string().trim().min(1).optional().describe("C\xF3digo exato do produto (opcional)."),
    limit: z4.number().int().min(1).max(100).default(25).describe("N\xFAmero m\xE1ximo de movimentos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let productId;
    if (code) {
      const { data: product, error: error2 } = await supabase.from("products").select("id").eq("code", code).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!product) {
        return { content: [{ type: "text", text: `Produto ${code} n\xE3o encontrado.` }], isError: true };
      }
      productId = product.id;
    }
    let query = supabase.from("stock_movements_unified").select("created_at,movement_type,quantity,reason,reference,notes,origem,product_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (productId) query = query.eq("product_id", productId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { movements: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pwpfvawxyqfvvguddxoh";
var mcp_default = defineMcp({
  name: "contagem-stock-up",
  title: "Contagem Stock UP",
  version: "0.1.0",
  instructions: "Ferramentas de consulta do armaz\xE9m Contagem Stock UP: procurar produtos, ver stock por localiza\xE7\xE3o e coli, listar produtos em rutura ou negativos e consultar movimentos de stock recentes. Todas as consultas correm com a conta do utilizador autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, product_stock_default, low_stock_default, recent_movements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
